version: '3.6'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ant
      MONGO_INITDB_ROOT_PASSWORD: example

    ports:
      - 27017:27017

    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ant
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://ant:example@mongo:27017/

volumes:
  mongodata: